# Global configuration
global:
  imageRegistry: ''
  imagePullSecrets: []
  storageClass: ''

# Common labels
commonLabels: {}
commonAnnotations: {}

# MinIO Init Job configuration
minioInit:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minio
    tag: 'latest'
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi
  bucket: vaam-eat

# Extract PMTiles Job configuration
extractPmtiles:
  enabled: true
  image:
    registry: docker.io
    repository: debian
    tag: 'stable-slim'
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 5Gi
    accessModes:
      - ReadWriteOnce

# Upload PMTiles Job configuration
uploadPmtiles:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/minio
    tag: 'latest'
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi

# API application configuration
api:
  enabled: true
  image:
    registry: ''
    repository: vaam-eat-api
    tag: 'latest'
    pullPolicy: IfNotPresent
  replicaCount: 1
  env:
    AUTH_SECRET: 'bBOdRw82eYxyPkd9KakHp1DgrCUmdfug1XlW5gJQ08c='
    DATABASE_URL: 'postgresql://vaam-eat:vaam-eat-password@postgresql:5432/vaam-eat?ssl_mode=disable'
    S3_ENDPOINT: 'minio'
    S3_ACCESS_KEY: 'minio'
    S3_SECRET_KEY: 'minio123'
    S3_PORT: '9000' # Bitnami MinIO default API port
    S3_SCHEME: 'http'
    S3_BUCKET: 'vaam-eat'
    S3_CDN_URL: 'http://minio:9000'
    NEXT_PUBLIC_MAPS_PMTILES_MINIO_BASE_URL: 'http://minio:9000'
    NEXT_PUBLIC_MAPS_PMTILES_MINIO_BUCKET: 'vaam-eat'
    OTEL_EXPORTER_OTLP_ENDPOINT: 'http://jaeger-collector:4318'
    OTEL_EXPORTER_OTLP_PROTOCOL: 'grpc'
    REDIS_URL: 'redis://redis-master:6379'
    REDIS_PREFIX: 'eat:vaam:store_'
    EMAIL_SERVER_HOST: 'maildev'
    EMAIL_SERVER_PORT: '1025'
    EMAIL_SERVER_USER: ''
    EMAIL_SERVER_PASSWORD: ''
    EMAIL_FROM: 'noreply@example.com'
    APP_URL: 'http://localhost:3000'
    NEXTAUTH_URL: 'http://localhost:3000'
    EMGR_CDN: 'http://localhost:3000/api/images/resize'
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  service:
    type: ClusterIP
    ports:
      http: 3000
  ingress:
    enabled: false
    className: ''
    annotations: {}
    hosts:
      - host: vaam-eat.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

# Migration Job configuration
migration:
  enabled: true
  image:
    registry: ''
    repository: vaam-eat-migration
    tag: 'latest'
    pullPolicy: IfNotPresent
  env:
    DATABASE_URL: 'postgresql://vaam-eat:vaam-eat-password@postgresql:5432/vaam-eat?ssl_mode=disable'
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

# Maildev configuration
maildev:
  enabled: true
  image:
    registry: docker.io
    repository: maildev/maildev
    tag: 'latest'
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  service:
    type: ClusterIP
    ports:
      web: 1080
      smtp: 1025

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ''

# Pod Security Context
podSecurityContext: {}

# Security Context
securityContext: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
# Bitnami Redis configuration
common:
  enabled: true

redis:
  enabled: true
  master:
    service:
      type: ClusterIP
  replica:
    replicaCount: 0 # Disable replicas for simplicity, adjust as needed

# Bitnami Jaeger configuration
jaeger:
  enabled: true
  agent:
    enabled: true
  collector:
    enabled: true
  query:
    enabled: true
  service:
    type: ClusterIP

# Bitnami Adminer configuration
adminer:
  enabled: true
  service:
    type: ClusterIP
  env:
    ADMINER_DEFAULT_SERVER: postgres
    ADMINER_DEFAULT_USERNAME: vaam-eat
    ADMINER_DEFAULT_PASSWORD: vaam-eat-password
    ADMINER_DESIGN: dracula
    ADMINER_PLUGINS: 'tables-filter tinymce'

# Bitnami PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    username: vaam-eat
    password: vaam-eat-password
    database: vaam-eat
  primary:
    persistence:
      enabled: true
      size: 8Gi
      accessModes:
        - ReadWriteOnce
  service:
    type: ClusterIP

# Bitnami MinIO configuration
minio:
  enabled: true
  auth:
    rootUser: minio
    rootPassword: minio123
  defaultBuckets: 'vaam-eat' # Create default bucket
  console:
    enabled: true # Enable MinIO Console
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  service:
    type: ClusterIP
