import "@app/styles/globals.scss";

import type { Metadata } from "next";

import {
  mainThemes,
  themeDataKey,
} from "@app/components/theme-toggle/constants";
import { TRPCReactProvider } from "@app/trpc/react";
import { HydrateClient } from "@app/trpc/server";
import { ThemeProvider } from "next-themes";
import type { PropsWithChildren } from "react";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" suppressHydrationWarning data-theme="light">
      <TRPCReactProvider>
        <body>
          <HydrateClient>
            <ThemeProvider themes={mainThemes} storageKey={themeDataKey}>
              <SessionProvider>
                <div id="app">{children}</div>
              </SessionProvider>
            </ThemeProvider>
          </HydrateClient>
        </body>
      </TRPCReactProvider>
    </html>
  );
}
