---
{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaam-eat-aio.fullname" . }}-minio
  labels:
    {{- include "vaam-eat-aio.minio.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vaam-eat-aio.minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vaam-eat-aio.minio.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "vaam-eat-aio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: minio
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.minio.image.registry }}/{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.auth.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.auth.rootPassword | quote }}
            - name: MINIO_BROWSER_SESSION_DURATION
              value: {{ .Values.minio.env.MINIO_BROWSER_SESSION_DURATION | quote }}
            - name: MINIO_BROWSER_LOGIN_ANIMATION
              value: {{ .Values.minio.env.MINIO_BROWSER_LOGIN_ANIMATION | quote }}
          volumeMounts:
            - name: data
              mountPath: /bitnami/minio/data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.minio.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "vaam-eat-aio.fullname" . }}-minio-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}