---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaam-eat-aio.fullname" . }}-postgresql
  labels:
    {{- include "vaam-eat-aio.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.ports.postgresql }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "vaam-eat-aio.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}