---
{{- with .Values.db }}
{{- if .enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "common.names.fullname" $ }}-pg
  namespace: {{ include "common.names.namespace" $ }}
spec:
  instances: {{ include "common.tplvalues.render" ( dict "value" .instances "context" $ ) }}

  storage:
    size: {{ include "common.tplvalues.render" ( dict "value" .storage.size "context" $ ) }}
    storageClass: {{ include "common.tplvalues.render" ( dict "value" .storage.storageClass "context" $ ) }}
    
  resources: {{ include "common.tplvalues.render" ( dict "value" .resources "context" $ ) | nindent 4 }}
  
{{ end -}}
{{ end -}}